version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./db:/var/lib/mongodb
    networks:
      - node-network

  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/igitalent
    depends_on:
      - mongodb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge